### ISSUE TITLE
Startup failed: character string expected as first argument

### ISSUE THREAD

**Issue by nicoFhahn** [cran/RInno#3]
Hey,
I tried to create the example app but everytime I try to launch the final product, I get the following error:

Startup failed with error(s):
character string expected as first argument

**Comment by singular-instruction** [comment]
Why did you close this issue? I am facing the same problem, did you find a solution?

**Comment by gaborcsardi** [comment]
This is a read only mirror of CRAN, please see the DESCRIPTION file for the package authors and the correct issue tracker.
